### ISSUE TITLE
Memory leaks on exit in some examples.

### ISSUE THREAD

**Issue by Bananaft** [Interrupt/delve-framework#13]
error(gpa): memory address 0x23b0e220200 leaked:

this is what I get when I exit some of the examples. namely:
clear,
lua,
sprite-animation

might happen in others but not persistently.

Win10 64

**Comment by Bananaft** [comment]
full log:
[log.txt](https://github.com/Interrupt/delve-framework/files/15283693/log.txt)

**Comment by Interrupt** [comment]
Thanks! I'll check these out

**Comment by Interrupt** [comment]
@Bananaft are these fixed for you in the latest version? I'm not getting any leak errors when running the examples with `--release=safe`
