### ISSUE TITLE
What is the license of the delve-framework?

### ISSUE THREAD

**Issue by photex** [Interrupt/delve-framework#16]
Howdy!

Been watching and enjoying this project and it only just occurred to me that I didn't see any mention of a license anywhere.

Could you clarify what your plans are regarding this?

Thanks 🙇

**Comment by photex** [comment]
I did a bit of brief reading on the differences between these two and my understanding is that neither of those would require that any forks shared their changes, but Apache requires that changes are at least disclosed if a product were to fork and use a modified version of the framework.

I think I might adopt Apache for https://github.com/photex/ziege now.

**Comment by Interrupt** [comment]
I settled on the MIT license - seems like the best path if people want to possibly use the framework for commercial use.

**Comment by Interrupt** [comment]
Added license
