### ISSUE TITLE
Vulkan backend not working on linux

### ISSUE THREAD

**Issue by stark26583** [Interrupt/delve-framework#25]
Creating Sokol App backend
Main loop starting
Sokol app starting main loop
Sokol app context initializing
Sokol setup backend: gfx.Backend.GLCORE

**Comment by Interrupt** [comment]
Oh, sorry. This was a misunderstanding on my part. The list of backends Sokol actually supports is:

**macOS**: Metal + GL4.1
**Windows**: D3D11 + GL4.3
**web**: WebGL2 + WebGPU
**iOS**: Metal + GLES3.0
**Android**: GLES3.0
**Linux**: GL4.3macOS: Metal + GL4.1
**Windows**: D3D11 + GL4.3
**web**: WebGL2 + WebGPU
**iOS**: Metal + GLES3.0
**Android**: GLES3.0
**Linux**: GL4.3

**Comment by stark26583** [comment]
Its fine thanks for clearing my doubt
