### ISSUE TITLE
Can't build with zig 0.11.0

### ISSUE THREAD

**Issue by nezvers** [Interrupt/delve-framework#5]
zig compiler is complaining about `ziglua` using `.root_source_file` which, I'm assuming, is updated for 0.12.x.
All libraries that are used ing `delve-framework` has been updated for 0.12.x.
I tried to make a pull request but I couldn't make the `build.zig` work with linking against `Delve`.

PS. `stb_image` is also included in [zig-gamedev](https://github.com/zig-gamedev/zig-gamedev/tree/main/libs/zstbi)

**Comment by Interrupt** [comment]
The version of ZigLua that we're pinned to should be the 0.11.0 version, are you sure you are building with 0.11.0? I haven't started work on upgrading to 0.12.0 yet but it might be time to start a branch at this point, but I'm wary about using that as the required version as there might be a bunch of breaking changes incoming.

It's still worth opening a WIP PR just to look at, I could help work through the build issues.
